/*
 * JoTour - Discover Jordan
 * Copyright (c) 2025 AlMa'ali group
 * All rights reserved.
*/

// Translations for 10 languages
const translations = {
    en: {
        "header.title": "JoTour",
        "header.subtitle": "Discover Jordan's Hidden Gems",
        "menu.home": "Home",
        "menu.language": "Language",
        "menu.reels": "Reels",
        "hero.title": "Experience Jordan Like Never Before",
        "hero.subtitle": "Authentic tours • Local guides • Unforgettable memories",
        "hero.explore": "Explore Tours",
        "tours.title": "Popular Tours",
        "tours.petra": "Petra Full Day",
        "tours.petra_desc": "Ancient city carved in rose-red cliffs",
        "tours.wadi": "Wadi Rum Desert",
        "tours.wadi_desc": "Mars-like landscape with Bedouin culture",
        "tours.deadsea": "Dead Sea Relaxation",
        "tours.deadsea_desc": "Float in the saltiest sea on Earth",
        "tours.guide": "Private guide",
        "tours.pickup": "Hotel pickup",
        "tours.lunch": "Lunch included",
        "tours.jeep": "Jeep safari",
        "tours.stars": "Stargazing",
        "tours.dinner": "Traditional dinner",
        "tours.spa": "Spa access",
        "tours.mud": "Mud treatment",
        "tours.resort": "Beach resort",
        "tours.book": "Book Now",
        "videos.title": "Experience Jordan Through Our Eyes",
        "videos.petra": "Petra Sunrise Magic",
        "videos.wadi": "Wadi Rum Adventure",
        "videos.deadsea": "Dead Sea Relaxation",
        "booking.title": "Book Your Tour",
        "booking.name": "Full Name",
        "booking.email": "Email",
        "booking.phone": "Phone Number",
        "booking.date": "Preferred Date",
        "booking.travelers": "Number of Travelers",
        "booking.person1": "1 Person",
        "booking.person2": "2 People",
        "booking.person3": "3 People",
        "booking.person4": "4 People",
        "booking.person5+": "5+ People",
        "booking.requests": "Special Requests",
        "booking.tour": "Tour",
        "booking.price": "Price",
        "booking.total": "Total",
        "booking.payment": "Payment Method",
        "booking.cash": "Cash on arrival",
        "booking.accept": "We accept USD, JOD, EUR as the way of payment. You will be given a receipt after payment.",
        "booking.complete": "Complete Booking",
        "whatsapp.service": "24 hours customer service"
    },
    es: {
        "header.title": "JoTour",
        "header.subtitle": "Descubre los Tesoros Escondidos de Jordania",
        "menu.home": "Inicio",
        "menu.language": "Idioma",
        "menu.reels": "Reels",
        "hero.title": "Experimenta Jordania Como Nunca Antes",
        "hero.subtitle": "Tours auténticos • Guías locales • Recuerdos inolvidables",
        "hero.explore": "Explorar Tours",
        "tours.title": "Tours Populares",
        "tours.petra": "Petra Día Completo",
        "tours.petra_desc": "Ciudad antigua tallada en acantilados de color rosa",
        "tours.wadi": "Desierto de Wadi Rum",
        "tours.wadi_desc": "Paisaje marciano con cultura beduina",
        "tours.deadsea": "Relajación en el Mar Muerto",
        "tours.deadsea_desc": "Flota en el mar más salado de la Tierra",
        "tours.guide": "Guía privado",
        "tours.pickup": "Recogida en hotel",
        "tours.lunch": "Almuerzo incluido",
        "tours.jeep": "Safari en jeep",
        "tours.stars": "Observación de estrellas",
        "tours.dinner": "Cena tradicional",
        "tours.spa": "Acceso al spa",
        "tours.mud": "Tratamiento de barro",
        "tours.resort": "Resort playero",
        "tours.book": "Reservar Ahora",
        "videos.title": "Experimenta Jordania a Través de Nuestros Ojos",
        "videos.petra": "Magia del Amanecer en Petra",
        "videos.wadi": "Aventura en Wadi Rum",
        "videos.deadsea": "Relajación en el Mar Muerto",
        "booking.title": "Reserva Tu Tour",
        "booking.name": "Nombre Completo",
        "booking.email": "Correo Electrónico",
        "booking.phone": "Número de Teléfono",
        "booking.date": "Fecha Preferida",
        "booking.travelers": "Número de Viajeros",
        "booking.person1": "1 Persona",
        "booking.person2": "2 Personas",
        "booking.person3": "3 Personas",
        "booking.person4": "4 Personas",
        "booking.person5+": "5+ Personas",
        "booking.requests": "Solicitudes Especiales",
        "booking.tour": "Tour",
        "booking.price": "Precio",
        "booking.total": "Total",
        "booking.payment": "Método de Pago",
        "booking.cash": "Efectivo al llegar",
        "booking.accept": "Aceptamos USD, JOD, EUR como método de pago. Se le entregará un recibo después del pago.",
        "booking.complete": "Completar Reserva",
        "whatsapp.service": "Servicio al cliente 24 horas"
    },
    fr: {
        "header.title": "JoTour",
        "header.subtitle": "Découvrez les Trésors Cachés de la Jordanie",
        "menu.home": "Accueil",
        "menu.language": "Langue",
        "menu.reels": "Reels",
        "hero.title": "Découvrez la Jordanie Comme Jamais Auparavant",
        "hero.subtitle": "Visites authentiques • Guides locaux • Souvenirs inoubliables",
        "hero.explore": "Explorer les Visites",
        "tours.title": "Visites Populaires",
        "tours.petra": "Pétra Journée Complète",
        "tours.petra_desc": "Ville antique taillée dans des falaises de couleur rose",
        "tours.wadi": "Désert de Wadi Rum",
        "tours.wadi_desc": "Paysage martien avec la culture bédouine",
        "tours.deadsea": "Détente à la Mer Morte",
        "tours.deadsea_desc": "Flotez sur la mer la plus salée de la Terre",
        "tours.guide": "Guide privé",
        "tours.pickup": "Navette hôtel",
        "tours.lunch": "Déjeuner inclus",
        "tours.jeep": "Safari en jeep",
        "tours.stars": "Observation des étoiles",
        "tours.dinner": "Dîner traditionnel",
        "tours.spa": "Accès au spa",
        "tours.mud": "Traitement à la boue",
        "tours.resort": "Station balnéaire",
        "tours.book": "Réserver Maintenant",
        "videos.title": "Découvrez la Jordanie à Travers Nos Yeux",
        "videos.petra": "Magie du Lever de Soleil à Pétra",
        "videos.wadi": "Aventure à Wadi Rum",
        "videos.deadsea": "Détente à la Mer Morte",
        "booking.title": "Réservez Votre Visite",
        "booking.name": "Nom Complet",
        "booking.email": "E-mail",
        "booking.phone": "Numéro de Téléphone",
        "booking.date": "Date Préférée",
        "booking.travelers": "Nombre de Voyageurs",
        "booking.person1": "1 Personne",
        "booking.person2": "2 Personnes",
        "booking.person3": "3 Personnes",
        "booking.person4": "4 Personnes",
        "booking.person5+": "5+ Personnes",
        "booking.requests": "Demandes Spéciales",
        "booking.tour": "Visite",
        "booking.price": "Prix",
        "booking.total": "Total",
        "booking.payment": "Méthode de Paiement",
        "booking.cash": "Espèces à l'arrivée",
        "booking.accept": "Nous acceptons USD, JOD, EUR comme moyen de paiement. Vous recevrez un reçu après le paiement.",
        "booking.complete": "Compléter la Réservation",
        "whatsapp.service": "Service client 24h/24"
    },
    de: {
        "header.title": "JoTour",
        "header.subtitle": "Entdecke Jordans Verborgene Schätze",
        "menu.home": "Startseite",
        "menu.language": "Sprache",
        "menu.reels": "Reels",
        "hero.title": "Erlebe Jordanien Wie Nie Zuvor",
        "hero.subtitle": "Authentische Touren • Einheimische Führer • Unvergessliche Erinnerungen",
        "hero.explore": "Touren Erkunden",
        "tours.title": "Beliebte Touren",
        "tours.petra": "Petra Ganztägig",
        "tours.petra_desc": "Antike Stadt, in rosarote Felsen gemeißelt",
        "tours.wadi": "Wadi Rum Wüste",
        "tours.wadi_desc": "Mars-ähnliche Landschaft mit Beduinenkultur",
        "tours.deadsea": "Entspannung am Toten Meer",
        "tours.deadsea_desc": "Schwimme im salzigsten Meer der Erde",
        "tours.guide": "Privatführer",
        "tours.pickup": "Hotelabholung",
        "tours.lunch": "Mittagessen inklusive",
        "tours.jeep": "Jeep-Safari",
        "tours.stars": "Sternenbeobachtung",
        "tours.dinner": "Traditionelles Abendessen",
        "tours.spa": "Spa-Zugang",
        "tours.mud": "Schlammbehandlung",
        "tours.resort": "Strandresort",
        "tours.book": "Jetzt Buchen",
        "videos.title": "Erlebe Jordanien Durch Unsere Augen",
        "videos.petra": "Petra Sonnenaufgang Magie",
        "videos.wadi": "Wadi Rum Abenteuer",
        "videos.deadsea": "Entspannung am Toten Meer",
        "booking.title": "Buche Deine Tour",
        "booking.name": "Vollständiger Name",
        "booking.email": "E-Mail",
        "booking.phone": "Telefonnummer",
        "booking.date": "Bevorzugtes Datum",
        "booking.travelers": "Anzahl der Reisenden",
        "booking.person1": "1 Person",
        "booking.person2": "2 Personen",
        "booking.person3": "3 Personen",
        "booking.person4": "4 Personen",
        "booking.person5+": "5+ Personen",
        "booking.requests": "Besondere Wünsche",
        "booking.tour": "Tour",
        "booking.price": "Preis",
        "booking.total": "Gesamt",
        "booking.payment": "Zahlungsmethode",
        "booking.cash": "Barzahlung bei Ankunft",
        "booking.accept": "Wir akzeptieren USD, JOD, EUR als Zahlungsmittel. Sie erhalten nach der Zahlung eine Quittung.",
        "booking.complete": "Buchung Abschließen",
        "whatsapp.service": "24 Stunden Kundenservice"
    },
    zh: {
        "header.title": "JoTour",
        "header.subtitle": "发现约旦的隐藏宝藏",
        "menu.home": "首页",
        "menu.language": "语言",
        "menu.reels": "Reels",
        "hero.title": "前所未有的约旦体验",
        "hero.subtitle": "正宗旅游 • 当地导游 • 难忘回忆",
        "hero.explore": "探索旅游",
        "tours.title": "热门旅游",
        "tours.petra": "佩特拉一日游",
        "tours.petra_desc": "雕刻在玫瑰色悬崖中的古城",
        "tours.wadi": "瓦迪拉姆沙漠",
        "tours.wadi_desc": "火星般的景观与贝都因文化",
        "tours.deadsea": "死海放松",
        "tours.deadsea_desc": "在地球上最咸的海中漂浮",
        "tours.guide": "私人导游",
        "tours.pickup": "酒店接送",
        "tours.lunch": "包含午餐",
        "tours.jeep": "吉普车 Safari",
        "tours.stars": "观星",
        "tours.dinner": "传统晚餐",
        "tours.spa": "水疗中心",
        "tours.mud": "泥浆治疗",
        "tours.resort": "海滩度假村",
        "tours.book": "立即预订",
        "videos.title": "通过我们的眼睛体验约旦",
        "videos.petra": "佩特拉日出魔法",
        "videos.wadi": "瓦迪拉姆冒险",
        "videos.deadsea": "死海放松",
        "booking.title": "预订您的旅游",
        "booking.name": "全名",
        "booking.email": "电子邮件",
        "booking.phone": "电话号码",
        "booking.date": "首选日期",
        "booking.travelers": "旅行者人数",
        "booking.person1": "1人",
        "booking.person2": "2人",
        "booking.person3": "3人",
        "booking.person4": "4人",
        "booking.person5+": "5+人",
        "booking.requests": "特殊要求",
        "booking.tour": "旅游",
        "booking.price": "价格",
        "booking.total": "总计",
        "booking.payment": "付款方式",
        "booking.cash": "抵达时现金支付",
        "booking.accept": "我们接受美元、约旦第纳尔、欧元作为支付方式。付款后您将收到收据。",
        "booking.complete": "完成预订",
        "whatsapp.service": "24小时客户服务"
    },
    ja: {
        "header.title": "JoTour",
        "header.subtitle": "ヨルダンの隠れた宝石を発見",
        "menu.home": "ホーム",
        "menu.language": "言語",
        "menu.reels": "リール",
        "hero.title": "これまでにないヨルダン体験",
        "hero.subtitle": "本格的なツアー • 地元のガイド • 忘れられない思い出",
        "hero.explore": "ツアーを探索",
        "tours.title": "人気のツアー",
        "tours.petra": "ペトラ一日ツアー",
        "tours.petra_desc": "バラ色の崖に彫られた古代都市",
        "tours.wadi": "ワディラム砂漠",
        "tours.wadi_desc": "火星のような風景とベドウィン文化",
        "tours.deadsea": "死海リラクゼーション",
        "tours.deadsea_desc": "地球上で最も塩分の多い海で浮く",
        "tours.guide": "プライベートガイド",
        "tours.pickup": "ホテル送迎",
        "tours.lunch": "昼食付き",
        "tours.jeep": "ジープサファリ",
        "tours.stars": "星観察",
        "tours.dinner": "伝統的な夕食",
        "tours.spa": "スパアクセス",
        "tours.mud": "泥治療",
        "tours.resort": "ビーチリゾート",
        "tours.book": "今すぐ予約",
        "videos.title": "私たちの目を通してヨルダンを体験",
        "videos.petra": "ペトラの日の出の魔法",
        "videos.wadi": "ワディラムアドベンチャー",
        "videos.deadsea": "死海リラクゼーション",
        "booking.title": "ツアーを予約",
        "booking.name": "氏名",
        "booking.email": "メールアドレス",
        "booking.phone": "電話番号",
        "booking.date": "希望日",
        "booking.travelers": "旅行者の人数",
        "booking.person1": "1名",
        "booking.person2": "2名",
        "booking.person3": "3名",
        "booking.person4": "4名",
        "booking.person5+": "5名以上",
        "booking.requests": "特別なリクエスト",
        "booking.tour": "ツアー",
        "booking.price": "価格",
        "booking.total": "合計",
        "booking.payment": "支払い方法",
        "booking.cash": "到着時現金払い",
        "booking.accept": "支払い方法としてUSD、JOD、EURを受け付けています。支払い後に領収書をお渡しします。",
        "booking.complete": "予約を完了",
        "whatsapp.service": "24時間カスタマーサービス"
    },
    ru: {
        "header.title": "JoTour",
        "header.subtitle": "Откройте Скрытые Сокровища Иордании",
        "menu.home": "Главная",
        "menu.language": "Язык",
        "menu.reels": "Reels",
        "hero.title": "Познакомьтесь с Иорданией Как Никогда Раньше",
        "hero.subtitle": "Аутентичные туры • Местные гиды • Незабываемые воспоминания",
        "hero.explore": "Исследовать Туры",
        "tours.title": "Популярные Туры",
        "tours.petra": "Петра Полный День",
        "tours.petra_desc": "Древний город, высеченный в розовых скалах",
        "tours.wadi": "Пустыня Вади-Рам",
        "tours.wadi_desc": "Пейзаж, похожий на Марс, с бедуинской культурой",
        "tours.deadsea": "Расслабление на Мертвом Море",
        "tours.deadsea_desc": "Плавайте в самом соленом море на Земле",
        "tours.guide": "Личный гид",
        "tours.pickup": "Трансфер из отеля",
        "tours.lunch": "Включен обед",
        "tours.jeep": "Джип-сафари",
        "tours.stars": "Наблюдение за звездами",
        "tours.dinner": "Традиционный ужин",
        "tours.spa": "Доступ в спа",
        "tours.mud": "Грязевое лечение",
        "tours.resort": "Пляжный курорт",
        "tours.book": "Забронировать Сейчас",
        "videos.title": "Познакомьтесь с Иорданией Через Наши Глаза",
        "videos.petra": "Волшебство Восхода Солнца в Петре",
        "videos.wadi": "Приключение в Вади-Рам",
        "videos.deadsea": "Расслабление на Мертвом Море",
        "booking.title": "Забронируйте Ваш Тур",
        "booking.name": "Полное Имя",
        "booking.email": "Электронная почта",
        "booking.phone": "Номер Телефона",
        "booking.date": "Предпочтительная Дата",
        "booking.travelers": "Количество Путешественников",
        "booking.person1": "1 Человек",
        "booking.person2": "2 Человека",
        "booking.person3": "3 Человека",
        "booking.person4": "4 Человека",
        "booking.person5+": "5+ Человек",
        "booking.requests": "Особые Запросы",
        "booking.tour": "Тур",
        "booking.price": "Цена",
        "booking.total": "Итого",
        "booking.payment": "Способ Оплаты",
        "booking.cash": "Наличными по прибытии",
        "booking.accept": "Мы принимаем USD, JOD, EUR в качестве способа оплаты. Вы получите квитанцию после оплаты.",
        "booking.complete": "Завершить Бронирование",
        "whatsapp.service": "Клиентская служба 24 часа"
    },
    ar: {
        "header.title": "جوتور",
        "header.subtitle": "اكتشف كنوز الأردن الخفية",
        "menu.home": "الرئيسية",
        "menu.language": "اللغة",
        "menu.reels": "رييلز",
        "hero.title": "اختبر الأردن كما لم تفعل من قبل",
        "hero.subtitle": "جولات أصيلة • مرشدون محليون • ذكريات لا تُنسى",
        "hero.explore": "استكشف الجولات",
        "tours.title": "جولات شعبية",
        "tours.petra": "البترا يوم كامل",
        "tours.petra_desc": "مدينة قديمة منحوتة في المنحدرات الوردية",
        "tours.wadi": "صحراء وادي رم",
        "tours.wadi_desc": "مناظر تشبه المريخ مع ثقافة البدو",
        "tours.deadsea": "الاسترخاء في البحر الميت",
        "tours.deadsea_desc": "تعوّم في أبحر ماء مالح على وجه الأرض",
        "tours.guide": "مرشد خاص",
        "tours.pickup": "النقل من الفندق",
        "tours.lunch": "الغداء مشمول",
        "tours.jeep": "رحلة سفاري بالجيب",
        "tours.stars": "مراقبة النجوم",
        "tours.dinner": "عشاء تقليدي",
        "tours.spa": "الدخول إلى السبا",
        "tours.mud": "علاج الطين",
        "tours.resort": "منتجع شاطئي",
        "tours.book": "احجز الآن",
        "videos.title": "اختبر الأردن من خلال أعيننا",
        "videos.petra": "سحر شروق الشمس في البتراء",
        "videos.wadi": "مغامرة وادي رم",
        "videos.deadsea": "الاسترخاء في البحر الميت",
        "booking.title": "احجز جولتك",
        "booking.name": "الاسم الكامل",
        "booking.email": "البريد الإلكتروني",
        "booking.phone": "رقم الهاتف",
        "booking.date": "التاريخ المفضل",
        "booking.travelers": "عدد المسافرين",
        "booking.person1": "شخص واحد",
        "booking.person2": "شخصان",
        "booking.person3": "3 أشخاص",
        "booking.person4": "4 أشخاص",
        "booking.person5+": "5+ أشخاص",
        "booking.requests": "طلبات خاصة",
        "booking.tour": "الجولة",
        "booking.price": "السعر",
        "booking.total": "المجموع",
        "booking.payment": "طريقة الدفع",
        "booking.cash": "الد
